//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Resource.rc 使用
//
#define IDD_DIALOG_MAIN                 101
#define IDD_DIALOG_Editor               102
#define IDD_DIALOG_SectionTable         103
#define IDD_DIALOG_DirectoryTable       104
#define IDD_DIALOG_About                105
#define IDI_ICON_Small                  111
#define IDI_ICON_Big                    112
#define IDD_DIALOG_ImportTable_Detail   113
#define IDD_DIALOG_ExportTable_Detail   114
#define IDD_DIALOG_RelocationTable_Detail 115
#define IDD_DIALOG_ResourceTable_Detail 116
#define IDD_DIALOG_BoundImport_Detail   117
#define IDD_DIALOG_DebugTable_Detail    118
#define IDD_DIALOG_TLS_Detail           119
#define IDD_DIALOG_CreateShell          120
#define IDD_DIALOG_Inject               123
#define IDC_BUTTON_PE_Edit              1000
#define IDC_BUTTON_About                1001
#define IDC_BUTTON_Exit                 1002
#define IDC_LIST_Process                1003
#define IDC_LIST_Moudle                 1004
#define IDC_EDIT_EntryPoint             1005
#define IDC_BUTTON_Create_Shell         1005
#define IDC_EDIT_ImageBase              1006
#define IDC_BUTTON_Inject               1006
#define IDC_EDIT_SizeOfImage            1007
#define IDC_BUTTON_Uninstall            1007
#define IDC_EDIT_DelayImport_RAV        1008
#define IDC_EDIT_BaseOfData             1009
#define IDC_EDIT_SectionAlignment       1010
#define IDC_EDIT_FileAlignment          1011
#define IDC_EDIT_Subsystem              1012
#define IDC_EDIT_NumberOfSections       1013
#define IDC_EDIT_TimeDataStamp          1014
#define IDC_EDIT_Relocation_RAV         1015
#define IDC_EDIT_Checksum               1016
#define IDC_EDIT_SizeOfOptionalHeader   1017
#define IDC_EDIT_NumberOfRvaAndSize     1018
#define IDC_EDIT_Characteristics        1019
#define IDC_EDIT_Magic                  1020
#define IDC_BUTTON_Sections             1021
#define IDC_EDIT_ExportTable_Size       1021
#define IDC_BUTTON_Directories          1022
#define IDC_EDIT_Copyright_Size         1022
#define IDC_BUTTON_Close                1023
#define IDC_EDIT_COM_Size               1023
#define IDC_STATIC_EntryPoint           1024
#define IDC_EDIT_DelayImport_Size       1024
#define IDC_STATIC_ImageBase            1025
#define IDC_EDIT_ImprotTable_Size       1025
#define IDC_STATIC_SizeOfImage          1026
#define IDC_EDIT_IAT_Size               1026
#define IDC_EDIT_BaseOfCode             1027
#define IDC_EDIT_SizeOfHeaders          1028
#define IDC_STATIC_BaseOfCode           1029
#define IDC_EDIT_Exception_Size         1029
#define IDC_STATIC_BaseOfData           1030
#define IDC_EDIT_Security_Size          1030
#define IDC_STATIC_SectionAlignment     1031
#define IDC_EDIT_Relocation_Size        1031
#define IDC_STATIC_FileAlignment        1032
#define IDC_EDIT_Debug_Size             1032
#define IDC_STATIC_Magic                1033
#define IDC_EDIT_TlsTable_Size          1033
#define IDC_STATIC_Subsystem            1034
#define IDC_EDIT_Globalptr_Size         1034
#define IDC_STATIC_NumberOfSections     1035
#define IDC_EDIT_LoadConfig_Size        1035
#define IDC_STATIC_TimeDataStamp        1036
#define IDC_EDIT_BoundImport_Size       1036
#define IDC_STATIC_SizeOfHeaders        1037
#define IDC_STATIC_Characteristics      1038
#define IDC_STATIC_Checksum             1039
#define IDC_STATIC_SizeOfOptionalHeader 1040
#define IDC_STATIC_NumberOfRvaAndSize   1041
#define IDC_LIST_SectionTable           1043
#define IDC_BUTTON_OK                   1044
#define IDC_STATIC_ExportTable          1045
#define IDC_STATIC_ImprotTable          1046
#define IDC_STATIC_Resource             1047
#define IDC_STATIC_Exception            1048
#define IDC_STATIC_Security             1049
#define IDC_STATIC_Relocation           1050
#define IDC_STATIC_Debug                1051
#define IDC_STATIC_Copyright            1052
#define IDC_STATIC_Globalptr            1053
#define IDC_STATIC_TlsTable             1054
#define IDC_STATIC_LoadConfig           1055
#define IDC_STATIC_BoundImport          1056
#define IDC_STATIC_IAT                  1057
#define IDC_STATIC_DelayImport          1058
#define IDC_STATIC_COM                  1059
#define IDC_STATIC_Reserved             1060
#define IDC_BUTTON_ExportTable_Detail   1061
#define IDC_BUTTON_ImprotTable_Detail   1062
#define IDC_BUTTON_ResourceTable_Detail 1063
#define IDC_BUTTON_COM_Detail           1064
#define IDC_BUTTON_TlsTable_Detail      1065
#define IDC_BUTTON_Relocation_Detail    1066
#define IDC_BUTTON_BoundImport_Detail   1067
#define IDC_BUTTON_Debug_Detail         1068
#define IDC_BUTTON_Copyright_Detail     1069
#define IDC_EDIT_ExportTable_RAV        1070
#define IDC_EDIT_ImprotTable_RAV        1071
#define IDC_EDIT_Resource_RAV           1072
#define IDC_EDIT_Resource_Size          1073
#define IDC_EDIT_Exception_RAV          1074
#define IDC_EDIT_Security_RAV           1075
#define IDC_EDIT_Debug_RAV              1076
#define IDC_EDIT_Copyright_RAV          1077
#define IDC_EDIT_Globalptr_RAV          1078
#define IDC_EDIT_TlsTable_RAV           1079
#define IDC_EDIT_LoadConfig_RAV         1080
#define IDC_EDIT_BoundImport_RAV        1081
#define IDC_EDIT_IAT_RAV                1082
#define IDC_EDIT_COM_RAV                1083
#define IDC_EDIT_Reserved_RAV           1084
#define IDC_EDIT_Reserved_Size          1085
#define IDC_LIST_DLL_List               1091
#define IDC_LIST_API_List               1092
#define IDC_EDIT_ExportTable_Offset     1094
#define IDC_EDIT_Base                   1096
#define IDC_EDIT_Name                   1097
#define IDC_EDIT_NameString             1098
#define IDC_EDIT_NumberOfFunctions      1099
#define IDC_EDIT_NumberOfNames          1100
#define IDC_EDIT_AddressOfFunctions     1101
#define IDC_EDIT_AddressOfNames         1102
#define IDC_EDIT_AddressOfNameOrdinals  1103
#define IDC_LIST_TableList              1106
#define IDC_LIST_Blocks                 1107
#define IDC_LIST_BlockItem              1108
#define IDC_TREE_Resource               1110
#define IDC_EDIT_RootName               1111
#define IDC_EDIT_RootID                 1112
#define IDC_EDIT3                       1113
#define IDC_EDIT4                       1114
#define IDC_EDIT5                       1115
#define IDC_EDIT6                       1116
#define IDC_EDIT7                       1117
#define IDC_TREE_BoundImport            1118
#define IDC_LIST_DebugTable             1119
#define IDC_EDIT_StartAddressOfRawData  1120
#define IDC_EDIT_ShellPath              1123
#define IDC_EDIT_EndAddressOfRawData    1124
#define IDC_EDIT_FilePath               1124
#define IDC_BUTTON_ShellPath            1125
#define IDC_BUTTON_FilePath             1126
#define IDC_EDIT_AddressOfIndex         1127
#define IDC_BUTTON_CreateShell          1127
#define IDC_EDIT_AddressOfCallBacks     1128
#define IDC_EDIT_SizeOfZeroFill         1129
#define IDC_EDIT_PID                    1130
#define IDC_EDIT_DLL                    1131
#define IDC_BUTTON_DLL                  1133
#define IDC_RADIO_RemoteThread          1134
#define IDC_RADIO_HiddenModule          1135
#define IDC_RADIO_HiddenModule_RemoteThread 1135
#define IDC_RADIO_2                     1136
#define IDC_RADIO_                      1136
#define IDC_RADIO_LoadProcess           1136
#define IDC_BUTTON_Inject_DLL           1137
#define IDC_RADIO_HiddenModule_SuspendThread 1137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
